### ISSUE TITLE
about result?

### ISSUE THREAD

**Issue by shz1314** [jacobkimmel/fcdensenet_pytorch#1]
Hi,
  i am very appreciate your work,i need use this network in my work.Do you achieve the result in the original paper?

**Comment by jacobkimmel** [comment]
hey there, I haven't tried to replicate the results in the paper. I don't work on natural images, so it's a bit orthogonal to my interests. I can confirm the network works effectively for biomedical image data sets. 

If you replicate the results in the paper, let me know with a PR and I'll add that information to the repo!
